use MeshKit's config provider for threadsafe operations
meshery/meshery-traefik-mesh pull request #111
Opened 2021-08-31 18:41 UTC by Abhishek-kumar09

Signed-off-by: Abhishek-kumar09 <abhimait1909@gmail.com>

**Description**
Replace configprovider coming from meshery-adapter library with meshkit config provider

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-08-31 18:45 UTC, utkarsh-pro approved these changes
LGTM. That was quick :ok_hand:

2021-08-31 18:47 UTC, Revolyssup approved these changes

2021-08-31 18:51 UTC, sayantan1413 approved these changes

2021-09-08 04:42 UTC, leecalcote requested changes
Thank you, @Abhishek-kumar09 👍

2021-09-08 04:43 UTC, leecalcote approved these changes

2021-09-08 04:43 UTC, merged